name: dongi
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"

# * ----- dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.14
  syncfusion_flutter_charts: ^27.2.2
  appwrite: ^13.0.0
  image_picker: ^1.1.2
  fpdart: ^1.1.1
  go_router: ^14.6.2
  firebase_core: ^3.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  flutter_slidable: ^3.0.0
  intl: ^0.19.0
  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  uuid: ^4.5.1
  collection: ^1.17.1
  url_launcher: ^6.1.14
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true

  # * ----- assets
  assets:
    - assets/animations/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 200
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 900
