// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKh7z7IkA5U6pqpXO6HzvEH9iCGdsex00',
    appId: '1:493524608587:web:66d5bdaf52f2170d838fce',
    messagingSenderId: '493524608587',
    projectId: 'hero-73343',
    authDomain: 'hero-73343.firebaseapp.com',
    storageBucket: 'hero-73343.firebasestorage.app',
    measurementId: 'G-LBPGL6JFXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhYpyYkiN84rYFaGxYSlttsZp1ORQDZEI',
    appId: '1:493524608587:android:d0eab4ae9f066cc7838fce',
    messagingSenderId: '493524608587',
    projectId: 'hero-73343',
    storageBucket: 'hero-73343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZXLZDGfLO3ONX1VZ40JaqpitwAIaPS08',
    appId: '1:493524608587:ios:7bfec470c2634d83838fce',
    messagingSenderId: '493524608587',
    projectId: 'hero-73343',
    storageBucket: 'hero-73343.firebasestorage.app',
    iosBundleId: 'ir.dispose.dongi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8JqrL85a6BMdH0h94BMv9V8bUY9UXps',
    appId: '1:439074732981:ios:de9fa7d87084cf90c237fc',
    messagingSenderId: '439074732981',
    projectId: 'dispose-9ffc6',
    storageBucket: 'dispose-9ffc6.appspot.com',
    iosClientId:
        '439074732981-m5jd8365vi1c86gsqd01p5kietunucba.apps.googleusercontent.com',
    iosBundleId: 'ir.dispose.dongi',
  );
}